### ISSUE TITLE
Debug Build fails with SIGSEGV

### ISSUE THREAD

**Issue by DivineGod** [alacritty/alacritty#5731]
I noticed a hard crash when running a debug build

`cargo run` will crash with a SIGSEGV while `cargo run --release` works fine

### System

OS: MacOS, MacBook Pro M1 Pro
Version: (master) https://github.com/alacritty/alacritty/commit/e2b5219eb40eaf36d8255cd87c5202bbb8ba0825

### Logs
[Alacritty-96705.log](https://github.com/alacritty/alacritty/files/7791500/Alacritty-96705.log)

**Comment by DivineGod** [comment]
I tried `git bisect` to find a known good commit but I stopped after going back 1 year and getting some compilation errors

**Comment by DivineGod** [comment]
currently traced it to https://github.com/alacritty/alacritty/blob/master/alacritty/src/renderer/mod.rs#L1329

If I add an `info!("insert inner")` at the beginning it won't SIGSEGV... investigating further

**Comment by DivineGod** [comment]
once it does run the colors are all black both foreground and background. Cursor does blink.

**Comment by DivineGod** [comment]
config is only debug section btw.

**Comment by DivineGod** [comment]
https://github.com/alacritty/alacritty/blob/master/alacritty/src/renderer/mod.rs#L1337 looks like this is the offending line

**Comment by chrisduerr** [comment]
What's the actual backtrace? Sounds like it might be something inside your driver? The code itself definitely doesn't look particularly suspicious and you're the first I've ever heard of running into a segfault in debug mode.

**Comment by DivineGod** [comment]
Got this out of running `lldb ./target/debug/alacritty`

```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x80000000)
    frame #0: 0x00000001000f3d3c alacritty`alacritty::renderer::Atlas::insert_inner::hb250a991777037a7(self=0x00006000026106c0, glyph=0x000000016fdeedb0, active_tex=0x000000016fdf0f94) at mod.rs:1338:45
   1335	        let multicolor;
   1336	
   1337	        unsafe {
-> 1338	            gl::BindTexture(gl::TEXTURE_2D, self.id);
   1339	
   1340	            // Load data into OpenGL.
   1341	            let (format, buffer) = match &glyph.buffer {
Target 0: (alacritty) stopped.
```

I'm on a 14" MacBook Pro M1 Pro so it's most likely some weirdness with the new Apple Silicon and GPU drivers for it.

System report info

```
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro18,3
  Chip:	Apple M1 Pro
  Total Number of Cores:	10 (8 performance and 2 efficiency)
  Memory:	32 GB
  System Firmware Version:	7429.61.2
  OS Loader Version:	7429.61.2
```

**Comment by chrisduerr** [comment]
> I'm on a 14" MacBook Pro M1 Pro so it's most likely some weirdness with the new Apple Silicon and GPU drivers for it.

That would be my assumption, in which case we can't do anything about it and macOS isn't going to do anything about it. So just run it in release mode I guess.

**Comment by DivineGod** [comment]
```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x80000000)
  * frame #0: 0x00000001000f3d48 alacritty`alacritty::renderer::Atlas::insert_inner::hb250a991777037a7(self=0x0000600002622d60, glyph=0x000000016fdee980, active_tex=0x000000016fdf0b04) at mod.rs:1337:45
    frame #1: 0x00000001000f3ca0 alacritty`alacritty::renderer::Atlas::insert::h641b7a7f23965c47(self=0x0000600002622d60, glyph=0x000000016fdee980, active_tex=0x000000016fdf0b04) at mod.rs:1321:12
    frame #2: 0x00000001000f2b04 alacritty`alacritty::renderer::load_glyph::h0062ba128dee4761(active_tex=0x000000016fdf0b04, atlas=0x000000016fdf0a80, current_atlas=0x000000016fdf0a98, rasterized=0x000000016fdee980) at mod.rs:919:11
    frame #3: 0x00000001000f2d4c alacritty`_$LT$alacritty..renderer..LoaderApi$u20$as$u20$alacritty..renderer..LoadGlyph$GT$::load_glyph::hf1e5e1c84cfe4c18(self=0x000000016fdef520, rasterized=0x000000016fdee980) at mod.rs:955:9
    frame #4: 0x0000000100096620 alacritty`alacritty::renderer::GlyphCache::load_glyph::hc00643c247945253(self=0x000000016fdef140, loader=0x000000016fdef520, glyph=RasterizedGlyph @ 0x000000016fdee980) at mod.rs:314:9
    frame #5: 0x0000000100095f3c alacritty`alacritty::renderer::GlyphCache::get::h3df4eddcc5ba627c(self=0x000000016fdef140, glyph_key=GlyphKey @ 0x000000016fdee890, loader=0x000000016fdef520, show_missing=true) at mod.rs:270:31
    frame #6: 0x00000001000958c0 alacritty`alacritty::renderer::GlyphCache::load_glyphs_for_font::hb22bea79efa10973(self=0x000000016fdef140, font=(token = 1), loader=0x000000016fdef520) at mod.rs:181:13
    frame #7: 0x0000000100096cc4 alacritty`alacritty::renderer::GlyphCache::load_common_glyphs::h1f402f8366afeecd(self=0x000000016fdef140, loader=0x000000016fdef520) at mod.rs:365:9
    frame #8: 0x0000000100095660 alacritty`alacritty::renderer::GlyphCache::new::h4af98aa557ed9c58(rasterizer=Rasterizer @ 0x000000016fdef418, font=0x000000016fdef6a8, loader=0x000000016fdef520) at mod.rs:171:9
    frame #9: 0x000000010009b540 alacritty`alacritty::display::Display::new_glyph_cache::_$u7b$$u7b$closure$u7d$$u7d$::h367b23583c3c9067(api=LoaderApi @ 0x000000016fdef520) at mod.rs:361:48
    frame #10: 0x00000001000978e8 alacritty`alacritty::renderer::QuadRenderer::with_loader::he39fc9c7bffe9cfd(self=0x000000016fdf0a80, func={closure#0} @ 0x000000016fdefd20) at mod.rs:722:9
    frame #11: 0x0000000100130950 alacritty`alacritty::display::Display::new_glyph_cache::h9e61a3e5c365e706(dpr=2, renderer=0x000000016fdf0a80, config=0x000000016fdfdb48) at mod.rs:361:17
    frame #12: 0x000000010009a164 alacritty`alacritty::display::Display::new::h71f1bd0e5a6f1e03(config=0x000000016fdfdb48, event_loop=0x0000600000c1d870) at mod.rs:250:13
    frame #13: 0x0000000100107e8c alacritty`alacritty::window_context::WindowContext::new::h598702502b44b390(config=0x000000016fdfdb48, pty_config=0x000000016fdf7e10, window_event_loop=0x0000600000c1d870, proxy=EventLoopProxy<alacritty::event::Event> @ 0x000000016fdfa830) at window_context.rs:72:23
    frame #14: 0x0000000100118b8c alacritty`alacritty::event::Processor::create_window::ha83d9d87f3d98feb(self=0x000000016fdfd998, event_loop=0x0000600000c1d870, proxy=EventLoopProxy<alacritty::event::Event> @ 0x000000016fdfe520, options=TerminalOptions @ 0x000000016fdfe538) at event.rs:1214:30
    frame #15: 0x0000000100027bdc alacritty`alacritty::alacritty::h7194a2fc10132b17(options=Options @ 0x000000016fdfef10) at main.rs:186:5
    frame #16: 0x0000000100027134 alacritty`alacritty::main::h238bd08fcdb6ce27 at main.rs:79:17
    frame #17: 0x00000001000d3604 alacritty`core::ops::function::FnOnce::call_once::haaf506153cb645ac((null)=(alacritty`alacritty::main::h238bd08fcdb6ce27 at main.rs:61), (null)=<unavailable>) at function.rs:227:5
    frame #18: 0x00000001000f4578 alacritty`std::sys_common::backtrace::__rust_begin_short_backtrace::h55a866bc5b913ac5(f=(alacritty`alacritty::main::h238bd08fcdb6ce27 at main.rs:61)) at backtrace.rs:123:18
    frame #19: 0x000000010003f804 alacritty`std::rt::lang_start::_$u7b$$u7b$closure$u7d$$u7d$::h6099325c1440f240 at rt.rs:146:18
    frame #20: 0x0000000100552214 alacritty`std::rt::lang_start_internal::hc245c4266d131202 [inlined] core::ops::function::impls::_$LT$impl$u20$core..ops..function..FnOnce$LT$A$GT$$u20$for$u20$$RF$F$GT$::call_once::haa2614d8b36c2daa at function.rs:259:13 [opt]
    frame #21: 0x0000000100552208 alacritty`std::rt::lang_start_internal::hc245c4266d131202 [inlined] std::panicking::try::do_call::hed608bbfbbf4bef8 at panicking.rs:403:40 [opt]
    frame #22: 0x0000000100552208 alacritty`std::rt::lang_start_internal::hc245c4266d131202 [inlined] std::panicking::try::hbb4553a4f1bd94fc at panicking.rs:367:19 [opt]
    frame #23: 0x0000000100552208 alacritty`std::rt::lang_start_internal::hc245c4266d131202 [inlined] std::panic::catch_unwind::hfa517dc4dbf0fd9c at panic.rs:133:14 [opt]
    frame #24: 0x0000000100552208 alacritty`std::rt::lang_start_internal::hc245c4266d131202 [inlined] std::rt::lang_start_internal::_$u7b$$u7b$closure$u7d$$u7d$::h07f4a8c2fba5706e at rt.rs:128:48 [opt]
    frame #25: 0x0000000100552208 alacritty`std::rt::lang_start_internal::hc245c4266d131202 [inlined] std::panicking::try::do_call::h0f7528a4a32d01ca at panicking.rs:403:40 [opt]
    frame #26: 0x0000000100552208 alacritty`std::rt::lang_start_internal::hc245c4266d131202 [inlined] std::panicking::try::h3ae59fba589ee65b at panicking.rs:367:19 [opt]
    frame #27: 0x0000000100552208 alacritty`std::rt::lang_start_internal::hc245c4266d131202 [inlined] std::panic::catch_unwind::hc74e853193d89d19 at panic.rs:133:14 [opt]
    frame #28: 0x0000000100552208 alacritty`std::rt::lang_start_internal::hc245c4266d131202 at rt.rs:128:20 [opt]
    frame #29: 0x000000010003f7d0 alacritty`std::rt::lang_start::h089cf7b7f5ada74e(main=(alacritty`alacritty::main::h238bd08fcdb6ce27 at main.rs:61), argc=1, argv=0x000000016fdff3a8) at rt.rs:145:17
    frame #30: 0x0000000100028288 alacritty`main + 32
    frame #31: 0x00000001012010f4 dyld`start + 520
```
